name = "supabase-authserver"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "dist"


# Build configuration
[build]
command = "npm run build"

# Deployment configuration
[site]
bucket = "./dist"
